"$schema" = "https://starship.rs/config-schema.json"

# $username   : show the current username during a SSH session or when the user is changed
# $hostname   : show the hostname when connected to a SSH session
# $directory  : path to the current directory
# $git_branch : show branch name
# $git_commit : show commit hash when in detached HEAD
# $git_state  : show the current operation (ex: REBASING, MERGING, etc.)
# $line_break : split the prompt in 2 lines
# $container  : show the container name if inside a container
# $character  : success status of last command
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$line_break\
$container\
$character"""

add_newline = true

[directory]
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = ""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
