---
- name: Add git-core PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: safe

- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name:
      - bat
      - bubblewrap
      - build-essential
      - fd-find
      - fzf
      - git
      - git-delta
      - jq
      - pandoc
      - pipx
      - ripgrep
      - shellcheck
      - socat
      - stow
      - unzip
    state: present
