---
- name: Add ~/.local/bin to PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    state: present

- name: Set COLORTERM to truecolor
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export COLORTERM=truecolor"
    state: present

- name: Add bat alias
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'alias bat="batcat"'
    state: present

- name: Add batrg function
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "batrg() { rg --pretty \"$@\" | bat --plain; }"
    state: present

- name: Set BAT_THEME
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export BAT_THEME=OneHalfDark"
    state: present

- name: Add zoxide init to bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    regexp: '^eval "\$\(zoxide init bash\)"$'
    line: 'eval "$(zoxide init bash)"'
    insertafter: EOF
    state: present
