#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage: ./scripts/sync-agent-docs.sh [--stdout]

Generate AGENTS.md from the full CLAUDE.md body.
  --stdout   Print generated output to stdout instead of writing AGENTS.md
EOF
  exit 1
}

mode="write"
if [[ $# -gt 1 ]]; then
  usage
fi
if [[ $# -eq 1 ]]; then
  case "$1" in
    --stdout)
      mode="stdout"
      ;;
    *)
      usage
      ;;
  esac
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
source_file="${repo_root}/CLAUDE.md"
target_file="${repo_root}/AGENTS.md"

if [[ ! -f "${source_file}" ]]; then
  echo "Error: missing ${source_file}" >&2
  exit 1
fi

tmp_shared="$(mktemp)"
tmp_output="$(mktemp)"
trap 'rm -f "${tmp_shared}" "${tmp_output}"' EXIT

awk '
  BEGIN { in_body = 0 }
  {
    if (!in_body && $0 ~ /^## /) {
      in_body = 1
    }
    if (in_body) {
      print
    }
  }
  END {
    if (!in_body) {
      print "Error: could not find a section header (## ...) in CLAUDE.md" > "/dev/stderr"
      exit 2
    }
  }
' "${source_file}" > "${tmp_shared}"

cat > "${tmp_output}" <<'EOF'
# AGENTS.md

This file provides guidance to AGENTS.md-compatible coding assistants (for example, Codex CLI and Gemini CLI).

> AUTO-GENERATED from `CLAUDE.md` by `./scripts/sync-agent-docs.sh`.
> Edit `CLAUDE.md` and rerun the sync script. Do not edit this file manually.

EOF

cat "${tmp_shared}" >> "${tmp_output}"

if [[ "${mode}" == "stdout" ]]; then
  cat "${tmp_output}"
else
  mv "${tmp_output}" "${target_file}"
  echo "Updated ${target_file} from ${source_file}"
fi
