---
- name: Core setup for WSL2
  hosts: localhost
  connection: local
  vars_files:
    - defaults.yml
    - vars.yml
  tasks:
    - name: Skip if not in playbooks_in_main_playbook
      ansible.builtin.meta: end_play
      when: playbooks_in_main_playbook is defined and 'core' not in playbooks_in_main_playbook

    - name: Create ~/repos directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/repos"
        state: directory
        mode: "0755"

    - name: Disable login message
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.hushlogin"
        state: touch
        modification_time: preserve
        access_time: preserve

    - ansible.builtin.import_tasks: tasks/apt-packages.yml
    - ansible.builtin.import_tasks: tasks/ansible-lint.yml
    - ansible.builtin.import_tasks: tasks/shell-config.yml
    - ansible.builtin.import_tasks: tasks/git.yml
    - ansible.builtin.import_tasks: tasks/difftastic.yml
    - ansible.builtin.import_tasks: tasks/zoxide.yml
